"""empty message

Revision ID: 64d074ce34aa
Revises: 0a293afa7cd6
Create Date: 2025-12-01 22:38:52.789010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d074ce34aa'
down_revision = '0a293afa7cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=40), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.String(length=40), nullable=False),
    sa.Column('terrain', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=40), nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('species')

    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    op.drop_table('planet')
    # ### end Alembic commands ###
